
steps:
- name: 'python:3.11-slim'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    cd app
    pip install -r requirements.txt
    # Add testing here
    python -m pytest tests/ --tb=short || echo "Tests optional"

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'
  - '-f'
  - 'app/Dockerfile'
  - 'app/'

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud run deploy ${_SERVICE_NAME} \
      --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA} \
      --region ${_REGION} \
      --platform managed \
      --no-allow-unauthenticated \  
      --port 8080

timeout: 900s

substitutions:
  _SERVICE_NAME: 'insight-agent'
  _REGION: 'us-central1'
  _REPO_NAME: 'insight-agent-repo'
  # REMOVED: _SHORT_SHA: 'latest' - Using Cloud Build's ${SHORT_SHA}

images:
- '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'